routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the 'web' middleware group. Now create something great!
  |
 */


Route::namespace('Web')->group(function () {
    Route::get('/', function () {
        return redirect(route('web.auth.login'));
    });
    Route::post('/attempt', ['uses' => 'AuthController@attempt', 'as' => 'web.auth.attempt']);
    Route::get('/logout', ['uses' => 'AuthController@logout', 'as' => 'web.auth.logout']);
    Route::get('/login', ['uses' => 'AuthController@login', 'as' => 'web.auth.login']);
    Route::get('/register', ['uses' => 'AuthController@register', 'as' => 'web.auth.register']);
    Route::post('/register', ['uses' => 'AuthController@registerAction', 'as' => 'web.auth.register']);
    Route::get('/password/reset', ['uses' => 'AuthController@reset', 'as' => 'password.reset']);
    Route::post('/password/reset', ['uses' => 'AuthController@sendReset', 'as' => 'web.auth.reset.send']);
    Route::post('/password/reset/confirm', ['uses' => 'AuthController@resetPassword', 'as' => 'web.auth.reset.confirm']);
});

Route::namespace('Web')->middleware('auth:web')->group(function () {
    Route::get('/user/profile', ['uses' => 'UserController@edit', 'as' => 'profile.edit']);
    Route::PUT('/user/profile', ['uses' => 'UserController@update', 'as' => 'profile.update']);
    Route::get('/user/password', ['uses' => 'UserController@editPassword', 'as' => 'password.edit']);
    Route::PUT('/user/password', ['uses' => 'UserController@updatePassword', 'as' => 'password.update']);
    // Route::get('/user/tickets', ['uses' => 'TicketsController@myTickets', 'as' => 'web.user.tickets']);
});

Route::prefix('admin')->attribute('namespace', 'Admin')->middleware('admin:web')->group(function () {
    Route::get('/', ['uses' => 'HomeController@index', 'as' => 'admin.home.index']);

    Route::prefix('order/{order}')->group(function () {
        Route::resource('products', 'OrderProductsController', ['as' => "admin.order"])
            ->parameter('products', 'orderProduct');
    });
    Route::get('/orders/export', ['uses' => 'OrdersController@export', 'as' => 'admin.orders.export']);
    Route::resource('orders', 'OrdersController', ['as' => 'admin']);
    Route::get('/products/export', ['uses' => 'ProductController@export', 'as' => 'admin.products.export']);
    Route::resource('products', 'ProductController', ['as' => 'admin']);
    Route::delete("product/{product}/image/{productImage}", "ProductController@deleteImage")->name("admin.product.image.destroy");
    Route::resource('routes', 'RoutesController', ['as' => 'admin']);
    Route::get('/users/export', ['uses' => 'UserController@export', 'as' => 'admin.users.export']);
    Route::resource('users', 'UserController', ['as' => 'admin']);
   
    Route::prefix('/user/{user}')->group(function () {
        Route::resource('devices', 'UserDevicesController', ['as' => "admin.user"])
            ->parameter('devices', 'userDevice');
    });

    Route::resource('locations', 'LocationsController', ['as' => 'admin']);
    route::get('/getRouteLocations', 'LocationsController@getRouteLocations')->name('getRouteLocations');
    Route::resource('categories', 'CategoriesController', ['as' => 'admin']);
    Route::resource('/groups', 'GroupController', ['as' => 'admin']);
    Route::resource('/permissions', 'PermissionController', ['as' => 'admin']);
    Route::prefix("/users/{user}")->group(function () {
        Route::resource("groups", "UserGroupsController", ['as' => "admin.users"]);
    });
    Route::resource('/groups', 'GroupController', ['as' => 'admin'])->parameter('group', 'group');
    Route::resource('/permissions', 'PermissionController', ['as' => 'admin']);

    Route::prefix('/group/{group}')->group(function () {
        Route::resource('permissions', 'GroupPermissionController', ['as' => "admin.group"])
            ->parameter('permissions', 'groupPermission');
    });

    // Route::resource('settings', 'SettingsController', ['as' => 'admin'])->only([
    //     "index", "edit", "update"
    // ]);
    Route::get('/logs', ['uses' => 'LogsController@index', 'as' => 'admin.logs.index']);
});

app/Models/User.php
<?php

namespace App\Models;

use App\Constants\UserTypes;
use App\Events\UserCreatedEvent;
use App\Events\UserDeletedEvent;
use App\Events\UserEditedEvent;
use App\Overrides\ResetPasswordNotification;
use Carbon\Carbon;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;

use PhpParser\Node\Expr\Array_;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{

    use Notifiable;
    use SoftDeletes;
    use CanResetPassword;

    protected $fillable =[
        'name',
        'password',
        'email',
        'phone',
        'status',
        'type',
        'route_id',
        'location_id',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($pass)
    {
        $this->attributes['password'] = \Hash::make($pass);
    }

    protected $attributes = [
        'type' => UserTypes::NORMAL
    ];

    public function groups()
    {
        return $this->belongsToMany(Group::class, 'user_groups', 'user_id', 'group_id');
    }


    public function devices()
    {
        return $this->hasMany(UserDevice::class, 'user_id', 'id');
    }

    public $dispatchesEvents = [
        'created' => UserCreatedEvent::class,
        'updated' => UserEditedEvent::class,
        'deleted' => UserDeletedEvent::class,
    ];

    public function hasAccess($permission, $permissible = null): bool
    {
        $userPermissions = $this->permissions();

        if (!$permissible || !count($this->permissionsData(get_class($permissible)))) {
            return in_array($permission, $userPermissions);
        }
        
        if (count($permissible->permissible) && Permissible::where('user_id', auth()->user()->id )->where('permissible_id', $permissible->id)->where('permissible_type', get_class($permissible))->first()) {
            return in_array($permission, $userPermissions);
        }
        return false;
    }

    public function permissions() : array
    {
        $permissions = $this->query()
            ->join("user_groups", "users.id", "=", "user_groups.user_id")
            ->join("groups", "user_groups.group_id", "=", "groups.id")
            ->join("group_permissions", "groups.id", "=", "group_permissions.group_id")
            ->join("permissions", "group_permissions.permission_id", "=", "permissions.id")
            ->select("permissions.identifier")
            ->where("users.id", "=", auth()->id())
            ->distinct()
            ->get();

        $permissionsIdentifier = [];
        foreach ($permissions as $permission) {
            $permissionsIdentifier[] = $permission["identifier"];
        }

        return $permissionsIdentifier;
    }

    public function permissionsData($modelType) : array
    {
        $permissions = $this->query()
            ->join("user_permissible", "users.id", "=", "user_permissible.user_id")
            ->select("user_permissible.permissible_id")
            ->where("users.id", "=", auth()->id())
            ->where("user_permissible.permissible_type", "=", $modelType)
            ->distinct()
            ->get();

        $permissionsIdsArray = [];
        foreach ($permissions as $permission) {
            $permissionsIdsArray[] = $permission["permissible_id"];
        }

        return $permissionsIdsArray;
    }

    public function isTypeOf($userType)
    {
        return ($this->type == $userType);
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function route()
    {
        return $this->belongsTo(Route::class);
    }
    public function location()
    {
        return $this->belongsTo(Location::class);
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Constants\UserTypes;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\UserRequest;
use App\Http\Services\UploaderService;
use App\Http\Services\UserService;
use App\Models\User;
use App\Models\Location;
use App\Models\Route;
use App\Repositories\UserRepository;
use View;

class UserController extends Controller
{
    protected $userService;
    private $userRepository;
    private $uploaderService;

    public function __construct(UserService $userService, UserRepository $userRepository, UploaderService $uploaderService)
    {
        $this->authorizeResource(User::class, "user");
        $this->userService = $userService;
        $this->userRepository = $userRepository;
        $this->uploaderService = $uploaderService;
    }

    public function index()
    {
        $this->authorize("index", User::class);
        $list = $this->userRepository->search(request())->paginate(10);
        $list->appends(request()->all());
        $count = $this->userRepository->search(request())->count();
        $types = UserTypes::getList();

        return View::make('admin.users.index', ['list' => $list, 'count' => $count, 'types' => $types,]);
    }

    public function create()
    {
        $locations = Location::where('active', 1)->get();
        $routes = Route::where('active', 1)->get();

        return View::make('admin.users.create', ['locations' => $locations, 'routes' => $routes]);
    }

    public function store(UserRequest $request)
    {
        $user = $this->userService->fillFromRequest($request);
        return redirect(route('admin.users.index'))->with('success', trans('item_added_successfully'));
    }

    public function edit(User $user)
    {
        $locations = Location::where('active', 1)->get();
        $routes = Route::where('active', 1)->get();

        return View::make('admin.users.edit', ['user' => $user, 'locations' => $locations, 'routes' => $routes]);
    }

    public function update(UserRequest $request, User $user)
    {
        $this->userService->fillFromRequest($request, $user);
        return redirect(route('admin.users.index'))->with('success', trans('item_updated_successfully'));
    }

    public function destroy(User $user)
    {
        if (in_array($user->id, [1, 2])) {
            return redirect()->back()->with('danger', trans('cant_delete_this_user'));
        }
        $this->uploaderService->deleteFile($user->image);
        $user->delete();

        return redirect()->back()->with('success', 'Item Deleted Successfully');
    }

    public function export()
    {
        return $this->userService->export();
    }
}

app/Http/Controllers/Api/UsersController.php
<?php

namespace App\Http\Controllers\Api;

use App\Constants\UserTypes;
use App\Http\Requests\Api\ProfileRequest;
use App\Http\Services\NotificationService;
use App\Http\Requests\Api\UserDevicesRequest;
use App\Http\Requests\Api\UploadPictureRequest;
use App\Http\Services\UserService;
use App\Models\UserDevice;
use App\Repositories\UserRepository;
use Illuminate\Foundation\Auth\User;
use Illuminate\Routing\Controller;
use Illuminate\Http\Response;
use Symfony\Component\HttpFoundation\Request;

class UsersController extends Controller
{
    protected $userService;
    protected $notificationService;
    protected $userRepository;

    public function __construct(UserService $userService, NotificationService $notificationService, UserRepository $userRepository)
    {
        $this->userService = $userService;
        $this->notificationService = $notificationService;
        $this->userRepository = $userRepository;
    }

    public function storeUserDevice(UserDevicesRequest $request)
    {
        if (!$userDevice = UserDevice::where('token', $request->request->get('token'))->first()) {
            $userDevice = $this->userService->fillUserDeviceFromRequest($request);
        }

        return response()->json($userDevice);
    }

    public function destroyUserDevice($token)
    {
        if ($device = UserDevice::where('token', $token)->first()) {
            UserDevice::destroy($device->id);
        }

        return response()->json([]);
    }
    
    public function updateProfile(ProfileRequest $request)
    {
        $this->userService->updateProfile($request);

        return response(['success' => true], Response::HTTP_CREATED);
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function resendPhoneVerified()
    {
        $this->userService->resetPhoneVerified();
        $this->notificationService->sendSMS(auth()->user(), auth()->user()->phone_verify);
        return response()->json(auth()->user())
            ->setStatusCode(Response::HTTP_OK);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function verifyPhone(Request $request)
    {
        try {
            $this->userService->verifyUserPhone($request);
        } catch (\Exception $e) {
            return response()->json($e->getMessage())
                ->setStatusCode($e->getCode());
        }
        return response()->json(auth()->user())
            ->setStatusCode(Response::HTTP_OK);
    }

    public function types()
    {
        $userTypes = UserTypes::getList();

        return response()->json($userTypes, 200);
    }

    public function points()
    {
        $balance = $this->userRepository->getPointsBalance(auth()->user()->id);

        return response()->json(['result' => $balance]);
    }

    public function uploadProfile(UploadPictureRequest $request)
    {
        $path = $this->userService->uploadProfilePicture($request);
        if ($path) {
            return response()->json(['success'=>true, 'result'=> $path]);
        }

        return response()->json(['success'=>false, 'result' => trans('failed_upload_profile_picture')]);
    }
}

app/Http/Controllers/Web/UserController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\BaseController;
use Illuminate\Http\Request;
use App\Models\User;
use App\Http\Requests;
use Illuminate\Routing\Redirector as RedirectorAlias;
use View;
use Auth;
use App\Http\Services\UserService;
use App\Http\Requests\Web\UserRequest;
use App\Http\Requests\Web\ChangePasswordRequest;

class UserController extends BaseController
{

    protected $userService;

    public function __construct(UserService $userService)
    {
        $this->userService = $userService;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        return View::make('web.user.edit', ['user' => auth()->user()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UserRequest $request
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request)
    {
        $this->userService->fillFromRequest($request, auth()->user());
        return redirect(route('profile.edit'))->with('success', trans('item_updated_successfully'));
    }

    /**
     * Update user password
     * @return \Illuminate\Contracts\View\View
     */
    public function editPassword()
    {
        return View::make('web.user.password', ['user' => auth()->user()]);
    }

    /**
     * @param ChangePasswordRequest $request
     * @return \Illuminate\Http\RedirectResponse|RedirectorAlias
     */
    public function updatePassword(ChangePasswordRequest $request)
    {
        if (!$this->userService->fillChangePasswordFromRequest($request, auth()->user())) {
            return redirect()->back()->with('error', trans('please_enter_correct_password'));
        }

        return redirect()->back()->with('success', trans('password_updated_successfully'));
    }

}

resources/views/admin/users/devices/index.blade.php
@extends('admin.layout')

@section('content')
<?php
    use \App\Constants\DeviceOS;
?>
    <div class="app-content">
        <section class="section">
            <!--page-header open-->
            <div class="page-header">
                <h4 class="page-title">{{trans('user_devices')}}</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/" class="text-light-color">{{trans('home')}}</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}" class="text-light-color">{{trans('users')}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{trans('user_devices')}}</li>
                </ol>
            </div>
            <!--page-header closed-->
            <div class="section-body">
                <div class="row">

                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <span class="table-add float-right">
                                     @can("create", UserDevice::class)
                                        <a href="{{ route('admin.user.devices.create', ['user' => $user->id]) }}" class="btn btn-icon">
                                            <i class="fa fa-plus fa-1x" aria-hidden="true"></i>
                                        </a>
                                    @endcan
                                </span>
                                <h4>{{trans('user_devices_list')}}</h4>
                            </div>

                            <div class="card-body">
                                @if(session()->has('success'))
                                    <div class="alert alert-success alert-has-icon alert-dismissible show fade">
                                        <div class="alert-icon"><i class="ion ion-ios-lightbulb-outline"></i></div>
                                        <div class="alert-body">
                                            <button class="close" data-dismiss="alert">
                                                <span>×</span>
                                            </button>
                                            <div class="alert-title">{{trans('success')}}</div>
                                            {{ session('success') }}
                                        </div>
                                    </div>
                                @endif
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover mb-0 text-nowrap">
                                        <thead>
                                            <tr>
                                                <th style="width: 1px">#</th>
                                                <th>{{trans('model')}}</th>
                                                <th>{{trans('os')}}</th>

                                                @if(auth()->user()->hasAccess("admin.user.devices.destroy"))
                                                    <th style="width: 1px">{{trans('actions')}}</th>
                                                @endif
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($list as $device)
                                            <tr>
                                                <td>{{ $device->id }}</td>
                                                <td>{{ $device->model }}</td>
                                                @foreach(DeviceOs::getList() as $key => $value)
                                                    @if($device->os == $key)
                                                        <td>{{$value}}</td>
                                                    @endif
                                                @endforeach

                                                @if(auth()->user()->hasAccess("admin.user.devices.destroy"))
                                                <td>
                                                    <div class="btn-group dropdown">
                                                        <button type="button" class="btn btn-sm btn-info m-b-5 m-t-5 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            <i class="fa-cog fa"></i>
                                                        </button>
                                                        <div class="dropdown-menu">
                                                            @can("delete", $device)
                                                                <button type="button" class="dropdown-item has-icon" data-toggle="modal" data-target="#delete_model_{{ $device->id }}">
                                                                    <i class="fa fa-trash"></i> {{trans('remove')}}
                                                                </button>
                                                            @endcan
                                                        </div>
                                                    </div>

                                                </td>
                                                @endif
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <div class="d-flex justify-content-center">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        @foreach ($list as $device)
        <!-- Message Modal -->
            <div class="modal fade" id="delete_model_{{ $device->id }}" tabindex="-1" role="dialog"  aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="example-Modal3">{{ trans('delete') }}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form action="{{ route('admin.user.devices.destroy', ['user'=>$device->user_id,'userDevice' => $device->id]) }}" method="Post" >
                            @method('DELETE')
                            @csrf
                            <div class="modal-body">
                            {{ trans('delete_confirmation_message') }}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-success" data-dismiss="modal">{{ trans('close') }}</button>
                                <button type="submit" class="btn btn-primary">{{ trans('delete') }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Message Modal closed -->
        @endforeach

    </div>
@stop

resources/views/admin/users/devices/new.blade.php
@extends('admin.layout')

@section('content')
<?php
    use \App\Constants\DeviceOS;
?>
    <div class="app-content">
        <section class="section">
            <!--page-header open-->
            <div class="page-header">
                <h4 class="page-title">{{trans('user_devices')}}</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('admin.home.index') }}" class="text-light-color">{{trans('home')}}</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('admin.user.devices.index', ['user' => $user->id]) }}" class="text-light-color">{{trans('user_devices')}}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{trans('new')}}</li>
                </ol>
            </div>
            <!--page-header closed-->
            <div class="section-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>{{trans('new_user_device')}}</h4>
                            </div>
                            <div class="card-body">
                                @include('admin.errors')
                                <form action="{{ route('admin.user.devices.store',['user'=>$user->id]) }}" method="post">
                                    @csrf
                                    <input type="hidden" name="user_id" value="{{$user->id}}">
                                    <div class="form-group col-md-6">
                                        <label for="model">{{ trans('model') }}</label>
                                        <input type="text" class="form-control" value="{{ old('model') }}" name="model" id="model" >
                                    </div>
                                    <div class="form-group col-md-6">
                                        <div class="form-group overflow-hidden">
                                            <label for="os">{{trans('os')}}</label>
                                            <select name="os"  class="form-control select2 w-100" id="os" >
                                                <option value="">{{ trans('select_os') }}</option>
                                                @foreach(DeviceOs::getList() as $key => $value)
                                                    <option value="{{ $key }}" >{{ $value }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <button type="submit" href="#" class="btn  btn-outline-primary m-b-5  m-t-5"><i class="fa fa-save"></i> {{trans('save')}}</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection