routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the 'web' middleware group. Now create something great!
  |
 */


Route::namespace('Web')->group(function () {
    Route::get('/', function () {
        return redirect(route('web.auth.login'));
    });
    Route::post('/attempt', ['uses' => 'AuthController@attempt', 'as' => 'web.auth.attempt']);
    Route::get('/logout', ['uses' => 'AuthController@logout', 'as' => 'web.auth.logout']);
    Route::get('/login', ['uses' => 'AuthController@login', 'as' => 'web.auth.login']);
    Route::get('/register', ['uses' => 'AuthController@register', 'as' => 'web.auth.register']);
    Route::post('/register', ['uses' => 'AuthController@registerAction', 'as' => 'web.auth.register']);
    Route::get('/password/reset', ['uses' => 'AuthController@reset', 'as' => 'password.reset']);
    Route::post('/password/reset', ['uses' => 'AuthController@sendReset', 'as' => 'web.auth.reset.send']);
    Route::post('/password/reset/confirm', ['uses' => 'AuthController@resetPassword', 'as' => 'web.auth.reset.confirm']);
});

Route::namespace('Web')->middleware('auth:web')->group(function () {
    Route::get('/user/profile', ['uses' => 'UserController@edit', 'as' => 'profile.edit']);
    Route::PUT('/user/profile', ['uses' => 'UserController@update', 'as' => 'profile.update']);
    Route::get('/user/password', ['uses' => 'UserController@editPassword', 'as' => 'password.edit']);
    Route::PUT('/user/password', ['uses' => 'UserController@updatePassword', 'as' => 'password.update']);
    // Route::get('/user/tickets', ['uses' => 'TicketsController@myTickets', 'as' => 'web.user.tickets']);
});

Route::prefix('admin')->attribute('namespace', 'Admin')->middleware('admin:web')->group(function () {
    Route::get('/', ['uses' => 'HomeController@index', 'as' => 'admin.home.index']);

    Route::prefix('order/{order}')->group(function () {
        Route::resource('products', 'OrderProductsController', ['as' => "admin.order"])
            ->parameter('products', 'orderProduct');
    });
    Route::get('/orders/export', ['uses' => 'OrdersController@export', 'as' => 'admin.orders.export']);
    Route::resource('orders', 'OrdersController', ['as' => 'admin']);
    Route::get('/products/export', ['uses' => 'ProductController@export', 'as' => 'admin.products.export']);
    Route::resource('products', 'ProductController', ['as' => 'admin']);
    Route::delete("product/{product}/image/{productImage}", "ProductController@deleteImage")->name("admin.product.image.destroy");
    Route::resource('routes', 'RoutesController', ['as' => 'admin']);
    Route::get('/users/export', ['uses' => 'UserController@export', 'as' => 'admin.users.export']);
    Route::resource('users', 'UserController', ['as' => 'admin']);
   
    Route::prefix('/user/{user}')->group(function () {
        Route::resource('devices', 'UserDevicesController', ['as' => "admin.user"])
            ->parameter('devices', 'userDevice');
    });

    Route::resource('locations', 'LocationsController', ['as' => 'admin']);
    route::get('/getRouteLocations', 'LocationsController@getRouteLocations')->name('getRouteLocations');
    Route::resource('categories', 'CategoriesController', ['as' => 'admin']);
    Route::resource('/groups', 'GroupController', ['as' => 'admin']);
    Route::resource('/permissions', 'PermissionController', ['as' => 'admin']);
    Route::prefix("/users/{user}")->group(function () {
        Route::resource("groups", "UserGroupsController", ['as' => "admin.users"]);
    });
    Route::resource('/groups', 'GroupController', ['as' => 'admin'])->parameter('group', 'group');
    Route::resource('/permissions', 'PermissionController', ['as' => 'admin']);

    Route::prefix('/group/{group}')->group(function () {
        Route::resource('permissions', 'GroupPermissionController', ['as' => "admin.group"])
            ->parameter('permissions', 'groupPermission');
    });

    // Route::resource('settings', 'SettingsController', ['as' => 'admin'])->only([
    //     "index", "edit", "update"
    // ]);
    Route::get('/logs', ['uses' => 'LogsController@index', 'as' => 'admin.logs.index']);
});

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Events\GroupEditedEvent;
use App\Events\GroupDeletedEvent;
use App\Events\GroupCreatedEvent;
class Group extends Model
{

    use Translatable;
    use SoftDeletes;

    protected $table = 'groups';
    public $translatedAttributes = ['name'];
    protected $fillable = ['active', 'type'];

    /**
     * The model's default values for attributes.
     *
     * @var array
     */
    protected $attributes = [
        'active' => 0
    ];

    public function users()
    {
        return $this->belongsToMany(User::class, 'user_groups', 'group_id', 'user_id');
    }

    public function permissions()
    {
        return $this->belongsToMany(Permission::class, 'group_permissions', 'group_id', 'permission_id')->withPivot("data", "id");
    }

    public $dispatchesEvents = [
        'updated' => GroupEditedEvent::class,
        'deleted' => GroupDeletedEvent::class,
        'created' => GroupCreatedEvent::class
    ];
}

app/Http/Controllers/Admin/GroupController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Group;
use Illuminate\Http\Request;
use App\Repositories\GroupRepository;
use App\Http\Requests\Admin\GroupRequest;
use App\Http\Services\GroupService;
use App\Http\Services\GroupPermissionService;
use View;

class GroupController extends Controller
{

    protected $groupService;
    protected $groupPermissionService;
    protected $groupRepository;

    public function __construct(GroupService $groupService, GroupPermissionService $groupPermissionService, GroupRepository $groupRepository)
    {
        $this->authorizeResource(Group::class, "group");

        $this->groupService = $groupService;
        $this->groupPermissionService = $groupPermissionService;
        $this->groupRepository = $groupRepository;
    }

    public function index()
    {
        $this->authorize("index", Group::class);

        $list = $this->groupRepository->search(request())->paginate(10);

        $list->appends(request()->all());
        return View::make('admin.groups.index', ['list' => $list]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View::make('admin.groups.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param GroupRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(GroupRequest $request)
    {
        $this->groupService->fillFromRequest($request);
        return redirect(route('admin.groups.index'))->with('success', trans('item_added_successfully'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Group $group
     * @return \Illuminate\Http\Response
     */
    public function edit(Group $group)
    {
        return View::make('admin.groups.edit', ['group' => $group]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param GroupRequest $request
     * @param Group $group
     * @return \Illuminate\Http\Response
     */
    public function update(GroupRequest $request, Group $group)
    {
        $this->groupService->fillFromRequest($request, $group);
        return redirect(route('admin.groups.index'))->with('success', trans('item_updated_successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Group $group
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Group $group)
    {
        $group->delete();
        return redirect()->back()->with('success', trans('item_deleted_successfully'));
    }
}

resources/views/admin/groups/create.blade.php
@extends('admin.layout')

@section('content')
<div class="app-content">
    <section class="section">

        <!--page-header open-->
        <div class="page-header">
            <h4 class="page-title">{{ trans('groups') }}</h4>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.home.index') }}" class="text-light-color">{{ trans('home') }}</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.groups.index') }}" class="text-light-color">{{ trans('groups') }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ trans('new') }}</li>
            </ol>
        </div>
        <!--page-header closed-->

        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>{{ trans('new_group') }}</h4>
                        </div>
                        <div class="card-body">
                            @include('admin.errors')
                            <form action="{{ route('admin.groups.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <ul class="nav nav-tabs" role="tablist">
                                    @foreach(config()->get('app.locales') as $lang => $language)
                                    <li class="nav-item">
                                        <a class="nav-link {{ $lang == app()->getLocale() ? 'active': ''}} show" id="home-tab2" data-toggle="tab" href="#lang-{{ $lang }}" role="tab" aria-controls="home" aria-selected="true">{{ $language }}</a>
                                    </li>
                                    @endforeach
                                </ul>
                                <div class="tab-content">
                                    @foreach(config()->get('app.locales') as $lang => $language)
                                    <div class="tab-pane fade {{ $lang == app()->getLocale() ? 'active show': ''}}" id="lang-{{ $lang }}" role="tabpanel" aria-labelledby="home-tab2">
                                        <div class="form-group col-md-4">
                                            <label for="name">{{ trans('name') }} *</label>
                                            <input type="text" class="form-control" name="{{ $lang }}[name]" id="name" value="{{ old( $lang.'.name' ) }}">
                                        </div>
                                    </div>
                                    @endforeach
                                </div>

                                <div class="form-group col-md-3">
                                    <label class="custom-switch">
                                        <input type="checkbox" name="active" value="1" class="custom-switch-input" {{ old('active') == 1 ? 'checked' : null }} >
                                               <span class="custom-switch-indicator"></span>
                                        <span class="custom-switch-description">{{ trans('active') }}</span>
                                    </label>
                                </div>
                                <div class="form-group col-md-3">
                                    <button type="submit" class="btn  btn-outline-primary m-b-5  m-t-5">
                                        <i class="fa fa-save"></i> {{ trans('save') }}
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@stop

resources/views/admin/groups/edit.blade.php
@extends('admin.layout')

@section('content')
<div class="app-content">
    <section class="section">

        <!--page-header open-->
        <div class="page-header">
            <h4 class="page-title">{{ trans('groups') }}</h4>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.home.index') }}" class="text-light-color">{{ trans('home') }}</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.groups.index') }}" class="text-light-color">{{ trans('groups') }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ trans('update_group') }} #{{ $group->id }}</li>
            </ol>
        </div>
        <!--page-header closed-->

        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>{{ trans('update_group') }}</h4>
                        </div>
                        <div class="card-body">
                            @include('admin.errors')
                            <form action="{{ route('admin.groups.update', ['group' => $group]) }}" method="Post" enctype="multipart/form-data" autocomplete="off" >
                                @method('PUT')
                                @csrf
                                <ul class="nav nav-tabs" role="tablist">
                                    @foreach(config()->get('app.locales') as $lang => $language)
                                    <li class="nav-item">
                                        <a class="nav-link {{ $lang == app()->getLocale() ? 'active': ''}} show" id="home-tab2" data-toggle="tab" href="#lang-{{ $lang }}" role="tab" aria-controls="home" aria-selected="true">{{ $language }}</a>
                                    </li>
                                    @endforeach
                                </ul>
                                <div class="tab-content">
                                    @foreach(config()->get('app.locales') as $lang => $language)
                                    <div class="tab-pane fade {{ $lang == app()->getLocale() ? 'active show': ''}}" id="lang-{{ $lang }}" role="tabpanel" aria-labelledby="home-tab2">
                                        <div class="form-group col-md-4">
                                            <label for="name">{{ trans('name') }} *</label>
                                            <input type="text" class="form-control" name="{{ $lang }}[name]" value="{{ !old( $lang.'.name') ? $group->translate($lang)->name : old( $lang.'.name') }} " id="{{ $lang }}[name]">
                                        </div>

                                    </div>
                                    @endforeach
                                </div>

                                <div class="form-group col-md-3">
                                    <label class="custom-switch">
                                        <input type="checkbox" name="active" value="1" class="custom-switch-input"  {{old("active",$group->active) == 1 ? "checked" : "" }} >
                                        <span class="custom-switch-indicator"></span>
                                        <span class="custom-switch-description">{{ trans('active') }}</span>
                                    </label>
                                </div>
                                <div class="form-group col-md-3">
                                    <button type="submit" href="#" class="btn  btn-outline-primary m-b-5  m-t-5"><i class="fa fa-save"></i> {{ trans('save') }}</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@stop

resources/views/admin/groups/index.blade.php
@extends('admin.layout')

@section('content')
<div class="app-content">
    <section class="section">

        <!--page-header open-->
        <div class="page-header">
            <h4 class="page-title">{{ trans('groups') }}</h4>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/" class="text-light-color">{{ trans('home') }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ trans('groups') }}</li>
            </ol>
        </div>
        <!--page-header closed-->
        <!--row open-->
        <div class="row">
            <div class="col-lg-12 col-xl-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h4>{{trans('filter_by')}}</h4>
                    </div>
                    <div class="card-body">
                        <form class="form-horizontal" type="get" action="{{ route("admin.groups.index") }}">
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <input type="text" placeholder="{{ trans('name') }}" class="form-control" value="{{ request("name") }}" name="name" >
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mt-1 mb-0">{{ trans("search") }}</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!--row closed-->
        <div class="section-body">
            <div class="row">

                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            @can('create',Group::class)
                            <span class="table-add float-right">
                                <a href="{{ route('admin.groups.create') }}" class="btn btn-icon"><i class="fa fa-plus fa-1x" aria-hidden="true"></i></a>
                            </span>
                            @endcan
                            <h4>{{ trans('groups_list') }}</h4>
                        </div>

                        <div class="card-body">
                            @if(session()->has('success'))
                            <div class="alert alert-success alert-has-icon alert-dismissible show fade">
                                <div class="alert-icon"><i class="ion ion-ios-lightbulb-outline"></i></div>
                                <div class="alert-body">
                                    <button class="close" data-dismiss="alert">
                                        <span>×</span>
                                    </button>
                                    <div class="alert-title">{{ trans('success') }}</div>
                                    {{ session('success') }}
                                </div>
                            </div>
                            @endif

                            <div class="table-responsive">
                                <table class="table table-bordered table-hover mb-0 text-nowrap">
                                    <thead>

                                        <tr>
                                            <th style="width: 1px">#</th>
                                            <th>{{ trans('name') }}</th>
                                            <th style="width: 1px">{{ trans('status') }}</th>
                                            <th style="width: 1px">{{ trans('actions') }}</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($list as $group)
                                        <tr>
                                            <td>{{ $group->id }}</td>
                                            <td>{{ $group->name }}</td>
                                            <td><span class="badge badge-{{ $group->active ? 'success' : 'danger' }}">{{ $group->active? trans('active') : trans('disabled') }}</span></td>
                                            <td>
                                                <div class="btn-group dropdown">
                                                    <button type="button" class="btn btn-sm btn-info m-b-5 m-t-5 dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="fa-cog fa"></i>
                                                    </button>
                                                    <div class="dropdown-menu">
                                                        @can('update', $group)
                                                            <a class="dropdown-item has-icon" href="{{ route('admin.groups.edit', ['group' => $group->id]) }}">
                                                                <i class="fa fa-edit"></i> {{ trans('edit') }}
                                                            </a>
                                                        @endcan
                                                        @can('delete', $group)
                                                            <button type="button" class="dropdown-item has-icon" data-toggle="modal" data-target="#delete_model_{{ $group->id }}">
                                                                <i class="fa fa-trash"></i>  {{ trans('remove') }}
                                                            </button>
                                                        @endcan
                                                        @can('index' , GroupPermission::class)
                                                        <a class="dropdown-item has-icon" href="{{ route('admin.group.permissions.index', ['group' => $group]) }}">
                                                            <i class="fa fa-edit"></i> {{ trans('permissions') }}
                                                        </a>
                                                        @endcan

                                                    </div>
                                                </div>

                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div class="d-flex justify-content-center">
                                {{ $list->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    @foreach ($list as $group)
    <!-- Message Modal -->
    <div class="modal fade" id="delete_model_{{ $group->id }}" tabindex="-1" role="dialog"  aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="example-Modal3">{{ trans('delete') }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('admin.groups.destroy', ['group' => $group]) }}" method="Post" >
                    @method('DELETE')
                    @csrf
                    <div class="modal-body">
                        {{ trans('are_you_sure_you_want_to_delete_this') }}?

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">{{ trans('close') }}</button>
                        <button type="submit" class="btn btn-primary">{{ trans('delete') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Message Modal closed -->
    @endforeach

</div>
@stop

resources/views/admin/groups/permissions.blade.php
@extends('admin.layout')

@section('content')
<?php
$lang = app()->getLocale();
?>

<div class="app-content">
    <section class="section">

        <!--page-header open-->
        <div class="page-header">
            <h4 class="page-title">{{trans('manage_permissions')}}</h4>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.home.index') }}" class="text-light-color">{{trans('home')}}</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.groups.index') }}" class="text-light-color">{{trans('groups')}}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{trans('manage_permissions')}}</li>
            </ol>
        </div>
        <!--page-header closed-->
        <div class="section-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>{{trans('manage_permissions')}}</h4>
                        </div>
                        <div class="card-body">

                            @if(session()->has('success'))
                            <div class="alert alert-success alert-has-icon alert-dismissible show fade">
                                <div class="alert-icon"><i class="ion ion-ios-lightbulb-outline"></i></div>
                                <div class="alert-body">
                                    <button class="close" data-dismiss="alert">
                                        <span>×</span>
                                    </button>
                                    <div class="alert-title">{{trans('success')}}</div>
                                    {{ session('success') }}
                                </div>
                            </div>
                            @endif

                            @include('admin.errors')
                            <form action="{{ route('admin.group.permissions.store', ['group' => $group]) }}" method="Post" autocomplete="off" >
                                @method('POST')
                                @csrf
                                <label>
                                    <input type="checkbox" name="select-all" id="select-all" />
                                    {{ trans('check_all') }}
                                </label>

                                <div class="form-group col-md-12 row">
                                    @foreach ($permissions as $permission)
                                    <div class="form-group mb-0 col-md-4">

                                        <label>
                                            <input type="checkbox" name="permissions[]"  value="{{$permission->id}}"  {{ ($group->permissions->contains('id', $permission->id)) ? 'checked' : '' }} >
                                            {{$permission->translate($lang)->name}}
                                        </label>

                                    </div>
                                    @endforeach

                                </div>

                                <div class="form-group col-md-12 row">
                                    <div class="form-group col-md-3">
                                        <button type="submit" href="#" class="btn  btn-outline-primary m-b-5  m-t-5">
                                            <i class="fa fa-save"></i> {{trans('save')}}</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@stop
@section('scripts')
<script>
    $('#select-all').click(function(event) {
        if(this.checked) {
            // Iterate each checkbox
            $(':checkbox').each(function() {
                this.checked = true;
            });
        } else {
            $(':checkbox').each(function() {
                this.checked = false;
            });
        }
    });
</script>
@stop